Primer versión del mapa de burbujas
IslasGECI/tamanio-poblacional-aves-marinas pull request #1
Opened 2019-08-27 23:06 UTC by efren-cabrera

Esta tarea está en la columna de implementación.

Anteriormente ya se había aprobado todo lo de go, python y sqlite. Falta revisar lo que está en la carpeta web (el _front-end_). También faltaría revisar el Dockerfile y el archivo de configuración de travis.

Ya está configurado para que cada que se haga un _push_ a la rama _develop_ automáticamente se actualice la aplicación en el servidor.

2019-08-27 23:16 UTC, efren-cabrera commented
@evaristor parece que cuando pides _pull request_ también piensa que estás en la rama _develop_, así que ahorita ya se publicó esta versión en el servidor http://islasgeci.org:850/.

2019-08-27 23:18 UTC, devarops commented
> @evaristor parece que cuando pides _pull request_ también piensa que estás en la rama _develop_, así que ahorita ya se publicó esta versión en el servidor http://islasgeci.org:850/.

@efren-cabrera: ¡Qué suave! Tal vez podamos ponerle en chiquto medio escondido por ahí el hash de la consignación para que nosotros sepamos cuál versión estamos viendo sin tener que meternos al servidor.

2019-08-30 00:32 UTC, devarops requested changes
El `Dockerfile` me parece maravilloso. Muchas gracias por llevarnos hacia un mejor lugar.

Revisé los archivos en la raíz. No revisé lo de Go, Python mi SQLite. En otra tanda revisaré lo de la carpeta Web.

2019-08-30 00:32 UTC, evaristor commented on .gitignore
> +
Por favor orden alfabéticamente y elimina espacios innecesarios

2019-08-30 00:32 UTC, evaristor commented on .travis.yml
> +- docker
La indentación no es adecuada. Por favor pásale el _Format Document_ del VSC

2019-08-30 00:32 UTC, evaristor commented on .travis.yml
> +      # Se asegura que no truene aunque la aplicación no esté corriendo
¿Convendría parar el contenedor antes? con algo similar a `docker stop ${NOMBRE_APLICACION}`

2019-08-30 00:32 UTC, evaristor commented on .travis.yml
> +      - sshpass -p ${PASSWORD_SERVIDOR} ssh -C ${USUARIO_VPS}@${SERVIDOR_VPS} "docker rm -f ${NOMBRE_APLICACION} || true"
```suggestion
      - sshpass -p ${PASSWORD_SERVIDOR} ssh -C ${USUARIO_VPS}@${SERVIDOR_VPS} "docker rm --force ${NOMBRE_APLICACION} || true"
```

2019-08-30 00:32 UTC, evaristor commented on .travis.yml
> +      - sshpass -p ${PASSWORD_SERVIDOR} ssh -C ${USUARIO_VPS}@${SERVIDOR_VPS} "docker run -d -p ${PUERTO}:4000 --name ${NOMBRE_APLICACION} tamanio-poblacional-aves-marinas:latest"
```suggestion
      - sshpass -p ${PASSWORD_SERVIDOR} ssh -C ${USUARIO_VPS}@${SERVIDOR_VPS} "docker run --detach --publish ${PUERTO}:4000 --name ${NOMBRE_APLICACION} tamanio-poblacional-aves-marinas:latest"
```

2019-08-30 00:32 UTC, evaristor commented on Makefile
> +	docker build -t tamanio-poblacional-aves-marinas .
```suggestion
	docker build --tag tamanio-poblacional-aves-marinas .
```

2019-08-30 00:32 UTC, evaristor commented on Makefile
> +	docker run -p 850:4000 tamanio-poblacional-aves-marinas:latest
```suggestion
	docker run --publish 850:4000 tamanio-poblacional-aves-marinas:latest
```

2019-08-30 00:32 UTC, evaristor commented on Makefile
> +	docker run -p 850:4000 tamanio-poblacional-aves-marinas:latest
¿Este no debería tener usar `--name`? Lo menciono porque lo usas en el Travis.

2019-09-04 17:15 UTC, efren-cabrera commented on .travis.yml
> +      # Se asegura que no truene aunque la aplicación no esté corriendo
Al forzar que se remueva el contenedor automáticamente se para, a mí me parece mejor parar y remover el contenedor en una solo instrucción.

2019-09-04 17:25 UTC, efren-cabrera commented
> > @evaristor parece que cuando pides _pull request_ también piensa que estás en la rama _develop_, así que ahorita ya se publicó esta versión en el servidor http://islasgeci.org:850/.
> 
> @efren-cabrera: ¡Qué suave! Tal vez podamos ponerle en chiquto medio escondido por ahí el hash de la consignación para que nosotros sepamos cuál versión estamos viendo sin tener que meternos al servidor.

Creo que esto podría ir en un _issue_

2019-09-05 20:46 UTC, nepito reviewed
Listo Efrén. Todo se ve bien excepto algunos nombre de variables.

2019-09-05 20:46 UTC, nepito commented on web/static/js/circle.js
> +    let circunferencia = radioTierra_m * Math.PI * 2;
```suggestion
    let perimetro = radioTierra_m * Math.PI * 2;
```
Nombre de `circunferencia` no me parece adecuada https://dle.rae.es/?id=9K0F6EK

2019-09-05 20:46 UTC, nepito commented on web/static/js/colors.js
> +    return `rgb(${valoresRGB[0]}, ${valoresRGB[1]}, ${valoresRGB[2]})`;
Si se repitieran las primeras tres letras del código ¿el color sería el mismo?

2019-09-05 20:46 UTC, nepito commented on web/static/js/draw.js
> +function sortByNestCount(element1, element2) {
No me parece que la función ordene algo. Creo que más compara, si es así tal vez el nombre debería de ser `compareNestCount`.

2019-09-05 20:46 UTC, nepito commented on web/static/js/draw.js
> +    d3.json("/tamanio", function (islas) {
`islas` es un mal nombre pues lo que tienes es una combinación de isla y especie.

2019-09-09 16:47 UTC, efren-cabrera commented on web/static/js/colors.js
> +    return `rgb(${valoresRGB[0]}, ${valoresRGB[1]}, ${valoresRGB[2]})`;
no, se deberían repetir las tres primeras letras para que sea el mismo color

2019-09-09 16:55 UTC, efren-cabrera commented on web/static/js/circle.js
> +    let circunferencia = radioTierra_m * Math.PI * 2;
En un círculo el perímetro y la circunferencia es lo mismo, pero cuando estas buscando ayuda sobre como dibujar círculos sobre mapas todos te hablan de la circunferencia de la tierra y no del perímetro de la tierra. Prefiero dejarlo como circunferencia, porque es el vocabulario que usan en esta área.

2019-09-10 20:59 UTC, devarops requested changes

2019-09-10 20:59 UTC, evaristor commented on Makefile
> +build: $(archivoDatos)
Por favor define los _phonies_ de forma explícita:

> explicitly declare the target to be phony by making it a prerequisite of the special target .PHONY

Referencia:

- [Phony Targets](https://www.gnu.org/software/make/manual/html_node/Phony-Targets.html)

2019-09-10 20:59 UTC, evaristor commented on web/static/js/data.js
> +            resolve(islas);
La línea 11 dice: `$.getJSON(`/islas`, islas => {`

¿Es correcto que la línea 22 diga: `$.getJSON(`/temporadas`, islas => {`?

Me suena a que en ligar de `islas` debería decir `teporadas`.

Me parece que en estas tres funciones hay código repetido.

2019-09-11 20:49 UTC, devarops approved these changes

2019-09-11 22:46 UTC, merged