Lanzamiento Versión 0.1.0
IslasGECI/tamanio-poblacional-aves-marinas pull request #10
Opened 2020-06-23 22:03 UTC by analislas

2020-06-23 22:18 UTC, devarops requested changes
@nepito: Por favor podrías?:

- [x] Evocar mutantes de Python con **Mutmut** en GitHub Actions
- [x] Correr una prueba _dummy_ con **Pytest** en GitHub Actions
- [x] Evalúa cambio de cobertura con **Codecov** en GitHub Actions
- [x] Verificar formato de Python con **Black** en GitHub Actions
- [x] Agregar _phony_ `lint` a `Makefile` para correr **Flake8** y **Pylint** (localmente, **no** en GitHub Actions)

Puedes seguir como ejemplo [geci_distance](https://github.com/IslasGECI/geci_distance/tree/feature/agrega_geci_distance)

2020-07-09 22:11 UTC, evaristor commented
![image](https://user-images.githubusercontent.com/3461018/87095868-71961c00-c1f6-11ea-8ad3-050b0c83b711.png)

2020-07-10 16:34 UTC, evaristor commented
@nepito @islasfernando Cambié la base de este _PR_ a `develop` (en lugar de `master`)
Por favor podrían confirmar que cumplí con el _checklist_ de calentamiento?

2020-07-13 18:02 UTC, nepito approved these changes
Listo @evaristor

2020-07-13 18:04 UTC, merged