Agrega una leyenda a la barrita de temporadas
IslasGECI/tamanio-poblacional-aves-marinas pull request #21
Opened 2020-12-16 18:24 UTC by xwalls

2021-01-11 22:14 UTC, nepito requested changes
Aquí te dejo la primera revisión :wink:

2021-01-11 22:14 UTC, nepito commented on front/public_html/css/style.css
> +} */
Por favor no consigne código comentado. Si lo vas a comentar mejor bórralo, de todas formas lo recordará el :git:.

2021-01-11 22:14 UTC, nepito commented on front/public_html/js/main.js
> +    bubble.innerHTML = "<p id='temporada'>"+temporadaActual+"</p>";
**Use template literals when contacting strings**:
¿Es posible cambiarlo a la siguiente manera:
```suggestion
    bubble.innerHTML = `<p id='temporada'>${temporadaActual}</p>`;
```
?

2021-01-11 22:14 UTC, nepito commented on front/public_html/js/main.js
> +        bubble.innerHTML = "<p id='temporada'>"+temporadaActual+"</p>";
Esto es código repetido ¿cómo lo podríamos refactorizar?

2021-01-13 20:37 UTC, xwalls commented on front/public_html/js/main.js
> +    bubble.innerHTML = "<p id='temporada'>"+temporadaActual+"</p>";
Para hacer ese cambio de sintaxis es necesario un cambio mayor eligiendo una tecnología distinta, en este caso se esta utilizando html y js puros.

2021-01-13 20:42 UTC, nepito commented on front/public_html/js/main.js
> +    bubble.innerHTML = "<p id='temporada'>"+temporadaActual+"</p>";
neta?!? qué mala bola. La sugerencia la tomé de [aquí](https://medium.com/javascript-in-plain-english/19-simple-javascript-coding-standards-to-keep-your-code-clean-7422d6f9bc0) y pensé que sí se podría. ¿Saber por qué no? lo pregunto para entender mejor.

2021-01-13 20:53 UTC, xwalls commented on front/public_html/css/style.css
> +} */
una disculpa, ya se mando la consignación con la limpieza hecha ✌

2021-01-13 20:57 UTC, xwalls commented on front/public_html/js/main.js
> +        bubble.innerHTML = "<p id='temporada'>"+temporadaActual+"</p>";
refactorizamos  esa porción de código en una función pero por como esta escrito actualmente el código, es necesario escribir ambos llamados a la función en la linea 29 y 59.

La primer linea (29) inicializa el valor del año de la temporada y
la segunda linea (59) actualiza dicho valor por el que se seleccione en el scroll.

2021-01-14 18:49 UTC, nepito requested changes
Listo @xwalls aquí va mi segunda revisión. Por favor, también atiende los puntos que faltaron de la primera.

2021-01-20 18:00 UTC, xwalls commented
atendiendo los comentarios de la primera revision,

-  `Será la variable de la línea 20 una constante, si sí usa const`
Analizando el uso de esta variable podemos afirmar que si es una constante.

- `Use template literals when contacting strings`
Hecho en tomate con nepo.

-  `Creo que no se utiliza la variable capa será posible quitarla`
Pareciera que así es pero, solamente la esta inicializando, para después usarla en el archivo draw.js
justo en este archivo, lo primero que revisa es que esa variable tenga ese mismo valor inicializado.

- `Creo que no se utiliza la variable circulos será posible quitarla`
Pareciera que así es pero, solamente la esta inicializando, para después usarla en el archivo draw.js
sin embargo hice la prueba de quitarlo y parece que si es necesaria esa inicialización pues las burbujas ya no se muestran.

- `Será la variable temporadas de la línea 16 una constante, si sí usa const`
Totalmente de acuerdo.

- `Será la variable especies de la línea 17 una constante, si sí usa const`
Totalmente de acuerdo.

- `Será la variable islas de la línea 18 una constante, si sí usa const`
Totalmente de acuerdo.

- `Será la variable overlay de la línea 44 una constante, si sí usa const `
Totalmente de acuerdo.

- `En las líneas 81 y 82 no utilizamos la variable index ¿es posible quitarla?`
lo mejor sera quitarla.

- `En las líneas 81 y 82 será posible Use ES6 arrow functions where possible`
Claro que si, probado y funcionando.

Muchas gracias por la revision nepo, definitivamente hay mucho que hacer aqui!

2021-01-20 18:24 UTC, nepito requested changes
Listo @xwalls. Muchas gracias por atender los comentarios :raised_hands: 

:thinking: ¿Cuáles crees que será las complicaciones de poner una prueba a la función que hiciste?

2021-01-20 18:24 UTC, nepito commented on Makefile
> +	docker run -d -p 8500:80 -it frontend_mapa_burbuja
Por favor agrega la versión larga de las instrucciones. ¿Serán las siguientes:
```suggestion
	docker run --detache --publish 8500:80 --interactive --tty frontend_mapa_burbuja 
```
?

2021-01-20 19:24 UTC, xwalls commented on Makefile
> +	docker run -d -p 8500:80 -it frontend_mapa_burbuja
Excelente @nepito, la simplifique un poco mas.
`docker run --detach --publish 8500:80 frontend_mapa_burbuja`

2021-01-20 19:31 UTC, xwalls commented on Makefile
> +	docker run -d -p 8500:80 -it frontend_mapa_burbuja
¿Cuáles crees que será las complicaciones de poner una prueba a la función que hiciste?
Necesitaríamos de una utilería de testing, recomiendo **Jest**, la instalaríamos y haríamos una prueba, te parece bien? 
@nepito 

- [https://jestjs.io/](https://jestjs.io/)

2021-01-20 19:45 UTC, xwalls commented on Makefile
> +	docker run -d -p 8500:80 -it frontend_mapa_burbuja
aunque recomiendo dejar las pruebas para un próximo PR,
porque si va implicar trabajo hacer esos cimientos, configuraciones extras y adaptar el proyecto actual para orientarlo a pruebas.

Aunque solo vayamos a agregar una sola prueba, va a ser todo un tema para abordar.

2021-01-20 23:37 UTC, nepito commented on Makefile
> +	docker run -d -p 8500:80 -it frontend_mapa_burbuja
> ¿Cuáles crees que será las complicaciones de poner una prueba a la función que hiciste?
> Necesitaríamos de una utilería de testing, recomiendo **Jest**, la instalaríamos y haríamos una prueba, te parece bien?
> @nepito
> 
> * https://jestjs.io/

`jest` me parece una buena opción :+1:

2021-01-20 23:40 UTC, nepito commented on Makefile
> +	docker run -d -p 8500:80 -it frontend_mapa_burbuja
> aunque recomiendo dejar las pruebas para un próximo PR,
> porque si va implicar trabajo hacer esos cimientos, configuraciones extras y adaptar el proyecto actual para orientarlo a pruebas.
> 
> Aunque solo vayamos a agregar una sola prueba, va a ser todo un tema para abordar.

¿Qué tanto trabajo nos puede tomar? ¿Cómo cuántos :tomato: le calculas? ¿Cómo entrarían esas pruebas, en la misma receta que ya hay de pruebas (con una modificación)? ¿En una receta distinta? ¿En un `Dockerfile` disitnto (lo pregunto porque hay muchos de esos en este repo)?

2021-01-21 00:02 UTC, xwalls commented on Makefile
> +	docker run -d -p 8500:80 -it frontend_mapa_burbuja
Actualmente y a simple vista donde se ve que se ocupa mas trabajo es en el proyecto del frontend,
mínimo unos 10 tomates,
sugiero dividir las cosas por lo menos de manera abstracta donde cada uno requerirá diferentes tipos de pruebas
(Pruebas para API y en el otro Pruebas de Código),

1.  Proyecto API de datos
2.  Proyecto API de lambdas
3.  Proyecto Frontend

   -  Orientar a pruebas e ir refactorizando poco a poco

Donde cada uno tiene su propio Dockerfile y estos son orquestados desde la raíz con del **docker compose**
hay un Dockerfile extra y aunque aun falta investigarlo mejor, creo que podrá desaparecer en algún momento.

2021-01-22 21:51 UTC, nepito commented on Makefile
> +	docker run -d -p 8500:80 -it frontend_mapa_burbuja
Muchas gracias por tu respuesta @xwalls . No me estoy imaginando que hagamos todas las pruebas en este _pr_. Me estoy imaginado que podamos hacer la prueba de la única función que hiciste `setSeason` y dejar el resto para otro _pr_ o para cuando estemos tocando el código. Mi interés es por lo siguiente: [En las reglas para programado](https://github.com/IslasGECI/manual#reglas-para-programadoras-y-programadores) el segundo punto dice que deberíamos de verificar la resistencia a mutaciones. Entiendo que eso es mucho, pero una avanzadita hacia esa dirección no suena mal. Es por eso que pregunto cuántos tomates necesitaremos para ver la prueba de la función `setSeason` en corriendo en GitHub Actions.

2021-01-22 22:03 UTC, xwalls commented on Makefile
> +	docker run -d -p 8500:80 -it frontend_mapa_burbuja
Gracias a ti @nepito por tu respuesta, necesitamos tener un tomate al respecto, te parece bien el día lunes o martes?

2021-07-05 18:11 UTC, devarops commented
Este PR es obsoleto. La última consignación fue hace cuatro meses.

2021-07-05 18:11 UTC, closed without merging